

/**
* Generated by ExoCoding 0.0.1
*/

import React from 'react';
import { useRoutes, RouteObject } from 'react-router-dom';
import { NewAgeTemplate } from '@/modules/main/pages/NewAgeTemplate';
import { LandingPageTemplate } from '@/modules/main/pages/LandingPageTemplate';
import { PasswordTemplate } from '@/modules/main/pages/PasswordTemplate';
import { Homepage } from '@/modules/main/pages/Homepage';
import { LoginTemplate } from '@/modules/main/pages/LoginTemplate';
import { MasterTemplate } from '@/modules/main/pages/MasterTemplate';
import { ComingSoonTemplate } from '@/modules/main/pages/ComingSoonTemplate';
import { NavbarTemplate } from '@/modules/main/pages/NavbarTemplate';
import { AccountTemplate } from '@/modules/main/pages/AccountTemplate';
import { Resume_Template } from '@/modules/main/pages/Resume_Template';
import { DashboardTemplate } from '@/modules/main/pages/DashboardTemplate';
import { SettingsTemplate } from '@/modules/main/pages/SettingsTemplate';

export const AppRoutes = () => {
  const routes: RouteObject[] = [
    { path: '/newagetemplate', element: <NewAgeTemplate /> },
    { path: '/landingpagetemplate', element: <LandingPageTemplate /> },
    { path: '/passwordtemplate', element: <PasswordTemplate /> },
    { path: '/', element: <Homepage /> },
    { path: '/logintemplate', element: <LoginTemplate /> },
    { path: '/mastertemplate', element: <MasterTemplate /> },
    { path: '/logintemplate', element: <LoginTemplate /> },
    { path: '/comingsoontemplate', element: <ComingSoonTemplate /> },
    { path: '/navbartemplate', element: <NavbarTemplate /> },
    { path: '/accounttemplate', element: <AccountTemplate /> },
    { path: '/resume_template', element: <Resume_Template /> },
    { path: '/dashboardtemplate', element: <DashboardTemplate /> },
    { path: '/settingstemplate', element: <SettingsTemplate /> }
  ];

  const element = useRoutes(routes);

  return <>{element}</>;
};
