package com.artsoft.testeexo.dto;

import javax.annotation.processing.Generated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Generated(value = "com.exocode.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class TABLE1ObjDTO {

  protected Long idTABLE1;
}