

/**
* Generated by ExoCoding 0.0.1
*/

import React from 'react';
import { useImmer } from 'use-immer';
import * as FontIcon from 'react-icons/fa';
import styles from './Homepage.module.css';
import useTitle from '@/hooks/useTitle';
import useBodystyle from '@/hooks/useBodystyle';
import { Button } from 'react-bootstrap';

type HomepageProps = {};

/**
* Hello World
*/
export const Homepage = (props: HomepageProps) => {

    useTitle('Homepage');

    return (
      <>
    
        <Button
            variant="primary"
            className={`${styles.skating_absent}`}
            
        >
                OK

        </Button>
    
      </>
    )
};
