

/**
* Generated by ExoCoding 0.0.1
*/

import React from 'react';
import { useImmer } from 'use-immer';
import * as FontIcon from 'react-icons/fa';
import styles from './LandingPageTemplate.module.css';
import useTitle from '@/hooks/useTitle';
import useBodystyle from '@/hooks/useBodystyle';
import { Container } from 'react-bootstrap';
import { Row } from 'react-bootstrap';
import { Col } from 'react-bootstrap';
import { Button } from 'react-bootstrap';
import { InputGroup } from 'react-bootstrap';
import { Form } from 'react-bootstrap';

type LandingPageTemplateProps = {};

/**
* LandingPage
*/
export const LandingPageTemplate = (props: LandingPageTemplateProps) => {

    useTitle('LandingPageTemplate');

    return (
      <>
    
    <Container fluid="fluid" className={`d-flex ${styles.menu}`}>
    
        <Row className={`${styles.rowmenu}`}>
    
    <Col sm={3} className={`d-flex ${styles.columnmenu}`}>
    
                <h1 className={`${styles.startbootstrap}`}>
                    Start Bootstrap
                </h1>
    
    </Col>
    
    
    <Col sm={3} className={`d-flex ${styles.columnbuttonmenu}`}>
    
        <Button
            variant="primary"
            className={`${styles.buttonmenu}`}
            
        >
                Sign Up

        </Button>
    
    </Col>
    
        </Row>
    
    </Container>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.banner}`}>
    
        <Row className={`${styles.rowbanner}`}>
    
                <h1 className={`${styles.labelbanner}`}>
                    Generate more leads with a professional landing page!
                </h1>
    
    
        <Row className={`${styles.rowsubmit}`}>
    
    <Col sm={9} className={`d-flex ${styles.columninputemail}`}>
    <Form.Group className={`${styles.inputemaill}`}>
        <Form.Label>
            
        </Form.Label>
        <InputGroup>
            <InputGroup.Text><FontIcon.FaEnvelope/></InputGroup.Text>
            <Form.Control
                type="email"
disabled={false}            />
        </InputGroup>
    </Form.Group>
    </Col>
    
    
    <Col sm={3} className={`d-flex ${styles.columninputsubmitbutton}`}>
    
        <Button
            variant="primary"
            className={`${styles.submitebuttoninputemail}`}
            
        >
                Submit

        </Button>
    
    </Col>
    
        </Row>
    
        </Row>
    
    </Container>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.threeoption}`}>
    
        <Row className={`${styles.rowthreeoption}`}>
    
    <Col sm={2} className={`d-flex ${styles.fullyresponsivecolumn}`}>
    
        <img className={`figure-img ${styles.fullyimage}`} src={`/assets/assets/templates/fully.png`} alt='' title=''/>
    
    
                <p className={`${styles.fullyresponsivelabel}`}>
                    Fully Responsive
                </p>
    
    
                <p className={`${styles.fullyresponsivetext}`}>
                    This theme will look great on any device, no matter the size!
                </p>
    
    </Col>
    
    
    <Col sm={2} className={`d-flex ${styles.bootstrap5readycolumn}`}>
    
        <img className={`figure-img ${styles.bootstrap5readyimage}`} src={`/assets/assets/templates/bootstrap.png`} alt='' title=''/>
    
    
                <p className={`${styles.bootstrap5ready}`}>
                    Bootstrap 5 Ready
                </p>
    
    
                <p className={`${styles.bootstrap5readytext}`}>
                    Featuring the latest build of the new Bootstrap 5 framework!
                </p>
    
    </Col>
    
    
    <Col sm={2} className={`d-flex ${styles.easytouse}`}>
    
        <img className={`figure-img ${styles.easytouseimage}`} src={`/assets/assets/templates/easytouse.png`} alt='' title=''/>
    
    
                <p className={`${styles.easytouselebal}`}>
                    Easy to Use
                </p>
    
    
                <p className={`${styles.easytousetext}`}>
                    Ready to use with your own content, or customize the source files!
                </p>
    
    </Col>
    
        </Row>
    
    </Container>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.design}`}>
    
        <Row className={`${styles.fullyresponsivedesign}`}>
    
    <Col sm={6} className={`d-flex ${styles.fullyresponsivecolumn}`}>
    
                <h1 className={`${styles.fullyresponsivedesignlabel}`}>
                    Fully Responsive Design
                </h1>
    
    
                <p className={`${styles.fullyresponsivedesigntext}`}>
                    When you use a theme created by Start Bootstrap, you know that the theme will look great on any device, whether it's a phone, tablet, or desktop the page will behave responsively!
                </p>
    
    </Col>
    
    
    <Col sm={6} className={`d-flex ${styles.fullyresponsivecolumnimage}`}>
    
        <img className={`figure-img ${styles.fullyresponsiveimage}`} src={`https://startbootstrap.github.io/startbootstrap-landing-page/assets/img/bg-showcase-1.jpg`} alt='' title=''/>
    
    </Col>
    
        </Row>
    
    
        <Row className={`${styles.updatedforbootstrap}`}>
    
    <Col sm={6} className={`d-flex ${styles.updatedforbootstrapcolumnimage}`}>
    
        <img className={`figure-img ${styles.updatedforbootstrapimage}`} src={`https://startbootstrap.github.io/startbootstrap-landing-page/assets/img/bg-showcase-2.jpg`} alt='' title=''/>
    
    </Col>
    
    
    <Col sm={6} className={`d-flex ${styles.updatedforbootstrapcolumn}`}>
    
                <h1 className={`${styles.updatedforbootstraplabel}`}>
                    Updated For Bootstrap 5
                </h1>
    
    
                <p className={`${styles.bootstraptext}`}>
                    Newly improved, and full of great utility classes, Bootstrap 5 is leading the way in mobile responsive web development! All of the themes on Start Bootstrap are now using Bootstrap 5!
                </p>
    
    </Col>
    
        </Row>
    
    
        <Row className={`${styles.easytousecustomize}`}>
    
    <Col sm={6} className={`d-flex ${styles.easytousecustomizecolumn}`}>
    
                <h1 className={`${styles.easytousecustomizelabel}`}>
                    Easy to Use & Customize
                </h1>
    
    
                <p className={`${styles.easytousecustomizetext}`}>
                    Landing Page is just HTML and CSS with a splash of SCSS for users who demand some deeper customization options. Out of the box, just add your content and images, and your new landing page will be ready to go!
                </p>
    
    </Col>
    
    
    <Col sm={6} className={`d-flex ${styles.easytousecustomizecolumn}`}>
    
        <img className={`figure-img ${styles.easytousecustomizeimage}`} src={`https://startbootstrap.github.io/startbootstrap-landing-page/assets/img/bg-showcase-3.jpg`} alt='' title=''/>
    
    </Col>
    
        </Row>
    
    </Container>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.peoplearesaying}`}>
    
                <h1 className={`${styles.whatpeoplearesaying}`}>
                    What people are saying...
                </h1>
    
    
        <Row className={`${styles.rowwhatpeoplearesaying}`}>
    
    <Col sm={3} className={`d-flex ${styles.whatpeoplearesayingcolumnmargaret}`}>
    
        <img className={`figure-img ${styles.whatpeoplearesayingimage}`} src={`/assets/assets/templates/testimonials-1.jpg`} alt='' title=''/>
    
    
                <p className={`${styles.margarete}`}>
                    Margaret E.
                </p>
    
    
                <p className={`${styles.margaretetext}`}>
                    This is fantastic! Thanks so much guys!
                </p>
    
    </Col>
    
    
    <Col sm={3} className={`d-flex ${styles.whatpeoplearesayingfred}`}>
    
        <img className={`figure-img ${styles.fredsimage}`} src={`/assets/assets/templates/testimonials-2.jpg`} alt='' title=''/>
    
    
                <p className={`${styles.freds}`}>
                    Fred S.
                </p>
    
    
                <p className={`${styles.fredstext}`}>
                    Bootstrap is amazing. Ive been using it to create lots of super nice landing pages.
                </p>
    
    </Col>
    
    
    <Col sm={3} className={`d-flex ${styles.whatpeoplearesayingsarah}`}>
    
        <img className={`figure-img ${styles.sarahwimage}`} src={`/assets/assets/templates/testimonials.png`} alt='' title=''/>
    
    
                <p className={`${styles.sarahw}`}>
                    Sarah W.
                </p>
    
    
                <p className={`${styles.sarahwtext}`}>
                    "Thanks so much for making these free resources available to us!"
                </p>
    
    </Col>
    
        </Row>
    
    </Container>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.signupnow}`}>
    
        <Row className={`${styles.rowimagebackground}`}>
    
                <h1 className={`${styles.readystarted}`}>
                    Ready to get started? Sign up now!
                </h1>
    
    
        <Row className={`${styles.singuprowemail}`}>
    
    <Col sm={9} className={`d-flex ${styles.columninputemail2}`}>
    <Form.Group className={`${styles.inputemail}`}>
        <Form.Label>
            
        </Form.Label>
        <InputGroup>
            <InputGroup.Text><FontIcon.FaEnvelope/></InputGroup.Text>
            <Form.Control
                type="email"
placeholder="Email Address"
required={true}
disabled={false}            />
        </InputGroup>
    </Form.Group>
    </Col>
    
    
    <Col sm={3} className={`d-flex ${styles.columnsubmitbutton}`}>
    
        <Button
            variant="primary"
            className={`${styles.email}`}
            
        >
                Submit

        </Button>
    
    </Col>
    
        </Row>
    
        </Row>
    
    </Container>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.footer}`}>
    
        <Row className={`${styles.fotterrow}`}>
    
    <Col sm={6} className={`d-flex ${styles.copyrightcolumn}`}>
    
                <p className={`${styles.copyrightlabel}`}>
                    © Your Website 2023. All Rights Reserved.
                </p>
    
    </Col>
    
    
    <Col sm={2} className={`d-flex ${styles.instagram}`}>
    
        <Button
            variant="primary"
            className={`${styles.buttoninstagram}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaInstagram />
    </div>
                null

        </Button>
    
    
        <Button
            variant="primary"
            className={`${styles.buttonfacebook}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaFacebookF />
    </div>
                null

        </Button>
    
    
        <Button
            variant="primary"
            className={`${styles.buttontwitter}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaTwitter />
    </div>
                null

        </Button>
    
    </Col>
    
        </Row>
    
    </Container>
    
      </>
    )
};
