

/**
* Generated by ExoCoding 0.0.1
*/

import React from 'react';
import { useImmer } from 'use-immer';
import * as FontIcon from 'react-icons/fa';
import styles from './LoginTemplate.module.css';
import useTitle from '@/hooks/useTitle';
import useBodystyle from '@/hooks/useBodystyle';
import { Row } from 'react-bootstrap';
import { Container } from 'react-bootstrap';
import { InputGroup } from 'react-bootstrap';
import { Form } from 'react-bootstrap';
import { Button } from 'react-bootstrap';

type LoginTemplateProps = {};

/**
* A simple login page
*/
export const LoginTemplate = (props: LoginTemplateProps) => {
      const [showPassword, setShowPassword] = React.useState<any>();

    useTitle('LoginTemplate');

    return (
      <>
    
        <Row className={`${styles.componentSvfmHrBmgI}`}>
    
    <Container fluid="md" className={`d-flex ${styles.componentCATFRGGmMF}`}>
    
                <h1 className={`${styles.componentWWADJKunxE}`}>
                    Sign In
                </h1>
    
    <Form.Group className={`${styles.componentbjDdEECruh}`}>
        <Form.Label>
            Email
        </Form.Label>
        <InputGroup>
            <InputGroup.Text><FontIcon.FaEnvelope/></InputGroup.Text>
            <Form.Control
                type="email"
disabled={false}            />
        </InputGroup>
    </Form.Group>
    <Form.Group className={`${styles.componentBnxhPXRFdq}`}>
        <Form.Label>
            Password
        </Form.Label>
        <InputGroup>
            <Form.Control
                type={showPassword ? 'text' : 'password'}
            />
            <Button variant="outline-secondary" onClick={() => setShowPassword(!showPassword)}>
                {showPassword ? <FontIcon.FaEyeSlash /> : <FontIcon.FaEye />}
            </Button>
        </InputGroup>
    </Form.Group>
    
        <Button
            variant="secondary"
            className={`${styles.componentFaucKikWcH}`}
            
        >
                Sign In

        </Button>
    
    </Container>
    
        </Row>
    
      </>
    )
};
