

/**
* Generated by ExoCoding 0.0.1
*/

import React from 'react';
import { useImmer } from 'use-immer';
import * as FontIcon from 'react-icons/fa';
import styles from './MasterTemplate.module.css';
import useTitle from '@/hooks/useTitle';
import useBodystyle from '@/hooks/useBodystyle';
import { Container } from 'react-bootstrap';

type MasterTemplateProps = {};

/**
* An almost empty page
*/
export const MasterTemplate = (props: MasterTemplateProps) => {

    useTitle('MasterTemplate');

    return (
      <>
    
    <Container fluid="fluid" className={`d-flex ${styles.hello_blank_page!}`}>
    
                <h1 className={`${styles.hello_blank_page!}`}>
                    Hello blank page
                </h1>
    
    </Container>
    
      </>
    )
};
