

/**
* Generated by ExoCoding 0.0.1
*/

import React from 'react';
import { useImmer } from 'use-immer';
import * as FontIcon from 'react-icons/fa';
import styles from './NewAgeTemplate.module.css';
import useTitle from '@/hooks/useTitle';
import useBodystyle from '@/hooks/useBodystyle';
import { Container } from 'react-bootstrap';
import { Row } from 'react-bootstrap';
import { Nav } from 'react-bootstrap';
import { Navbar } from 'react-bootstrap';
import { LinkContainer } from 'react-router-bootstrap';
import { NavDropdown } from 'react-bootstrap';
import { Button } from 'react-bootstrap';
import { Col } from 'react-bootstrap';

type NewAgeTemplateProps = {};

/**
* An almost emtpy page
*/
export const NewAgeTemplate = (props: NewAgeTemplateProps) => {

    useTitle('NewAgeTemplate');

    return (
      <>
    
    <Container fluid="fluid" className={`d-flex ${styles.newage}`}>
    
        <Row className={`${styles.prior_wooden}`}>
    
        <Row className={`${styles.menu}`}>
    

        <Navbar bg="" expand="lg" className={`${styles.cob_payment}`}>
            <Container>
                <Navbar.Brand >
                    
                    Start Bootstrap
                </Navbar.Brand>
                <Navbar.Toggle aria-controls="basic-navbar-nav" />
                <Navbar.Collapse id="basic-navbar-nav">
                    <Nav className="ms-auto">
                    </Nav>
                </Navbar.Collapse>
            </Container>
        </Navbar>
    
        </Row>
    
    
        <Button
            variant="primary"
            className={`${styles.sendfeedback}`}
            
        >
                Send Feedback

        </Button>
    
        </Row>
    
    </Container>
    
    
        <Row className={`${styles.showcase}`}>
    
        <Row className={`${styles.ziggurat_male}`}>
    
                <h1 className={`${styles.showcaselabel}`}>
                    Showcase your app beautifully.
                </h1>
    
    
                <p className={`${styles.launch}`}>
                    Launch your mobile app landing page faster with this free, open source theme from Start Bootstrap!
                </p>
    
    
        <Row className={`${styles.button}`}>
    
        <Form.Control
                type="image"
                className={`figure-img ${styles.male_distributed}`}
                
                
                src={`https://startbootstrap.github.io/startbootstrap-new-age/assets/img/google-play-badge.svg`}
                title=''
        />
    
    
        <Form.Control
                type="image"
                className={`figure-img ${styles.southwest_dollar}`}
                
                
                src={`https://startbootstrap.github.io/startbootstrap-new-age/assets/img/app-store-badge.svg`}
                title=''
        />
    
        </Row>
    
        </Row>
    
    
        <Row className={`${styles.salmon_senior}`}>
    
        <img className={`figure-img ${styles.berkshire_magenta}`} src={`/assets/assets/templates/showcase.png`} alt='' title=''/>
    
        </Row>
    
        </Row>
    
    
    <Col  className={`d-flex ${styles.tnwrow} bg-primary`}>
    
                <p className={`${styles.intuitive}`}>
                    "An intuitive solution to a common problem that we all face, wrapped up in a single app!"
                </p>
    
    
        <img className={`figure-img ${styles.licensed_orchestrator}`} src={`https://startbootstrap.github.io/startbootstrap-new-age/assets/img/tnw-logo.svg`} alt='' title=''/>
    
    </Col>
    
    
        <Row className={`${styles.devicemockups}`}>
    
    <Col sm={5} className={`d-flex ${styles.hollow_deliverables} bg-`}>
    
        <img className={`figure-img ${styles.phoneimage}`} src={`/assets/assets/templates/quality.png`} alt='' title=''/>
    
    </Col>
    
    
        <Row className={`${styles.that_card}`}>
    
    <Col sm={6} className={`d-flex ${styles.connect_squares} bg-`}>
    
        <img className={`figure-img ${styles.luxurious_trigender}`} src={`/assets/assets/templates/phone.png`} alt='' title=''/>
    
    
                <p className={`${styles.krone_harness}`}>
                    Device Mockups
                </p>
    
    
                <p className={`${styles.account_franc}`}>
                    Ready to use HTML/CSS device mockups, no Photoshop required!
                </p>
    
    </Col>
    
    
    <Col sm={6} className={`d-flex ${styles.electronic_avon} bg-`}>
    
        <img className={`figure-img ${styles.neptunium_north}`} src={`/assets/assets/templates/camera.png`} alt='' title=''/>
    
    
                <p className={`${styles.gasoline_fuchsia}`}>
                    Flexible Use
                </p>
    
    
                <p className={`${styles.circle}`}>
                    Put an image, video, animation, or anything else in the screen!
                </p>
    
    </Col>
    
    
    <Col sm={6} className={`d-flex ${styles.ram_heuristic} bg-`}>
    
        <img className={`figure-img ${styles.mini_robust}`} src={`/assets/assets/templates/gift.png`} alt='' title=''/>
    
    
                <p className={`${styles.or_generate}`}>
                    Free to Use
                </p>
    
    
                <p className={`${styles.arkansas_south}`}>
                    As always, this theme is free to download and use for any purpose!
                </p>
    
    </Col>
    
    
    <Col sm={6} className={`d-flex ${styles.streamline_benchmark} bg-`}>
    
        <img className={`figure-img ${styles.grotesque_indigo}`} src={`/assets/assets/templates/check.png`} alt='' title=''/>
    
    
                <p className={`${styles.handcrafted_concrete}`}>
                    Open Source
                </p>
    
    
                <p className={`${styles.green_unbranded}`}>
                    Since this theme is MIT licensed, you can use it commercially!
                </p>
    
    </Col>
    
        </Row>
    
        </Row>
    
    
        <Row className={`${styles.enteranewage}`}>
    
    <Col sm={5} className={`d-flex ${styles.ascii_program}`}>
    
                <h1 className={`${styles.corporate_jbod}`}>
                    Enter a new age of web design
                </h1>
    
    
                <p className={`${styles.webtext}`}>
                    This section is perfect for featuring some information about your application,why it was built, the problem it solves, or anything else! There's plenty of space for text here, so don't worry about writing too much.
                </p>
    
    </Col>
    
    
    <Col sm={6} className={`d-flex ${styles.white_small}`}>
    
        <img className={`figure-img ${styles.cheese_negligible}`} src={`https://images.unsplash.com/photo-1620207418302-439b387441b0?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=900&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY4MTg1MDA0OA&ixlib=rb-4.0.3&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=900`} alt='' title=''/>
    
    </Col>
    
        </Row>
    
    
        <Row className={`${styles.stopwaiting}`}>
    
        <Row className={`${styles.stopwaitinggradient}`}>
    
    <Col sm={7} className={`d-flex ${styles.architect_southwest}`}>
    
                <h1 className={`${styles.customer_wrongly}`}>
                    Stop waiting. Start building.
                </h1>
    
    
        <Button
            variant="primary"
            className={`${styles.buttondownload}`}
            
        >
                Download for free

        </Button>
    
    </Col>
    
        </Row>
    
        </Row>
    
    
        <Row className={`${styles.gettheappnow}`}>
    
        <Row className={`${styles.getappnow}`}>
    
                <h1 className={`${styles.macedonia_utah}`}>
                    Get the app now!
                </h1>
    
    
        <img className={`figure-img ${styles.joule_elegant}`} src={`https://startbootstrap.github.io/startbootstrap-new-age/assets/img/google-play-badge.svg`} alt='' title=''/>
    
    
        <img className={`figure-img ${styles.tandem_table}`} src={`https://startbootstrap.github.io/startbootstrap-new-age/assets/img/app-store-badge.svg`} alt='' title=''/>
    
        </Row>
    
    
        <Row className={`${styles.pennsylvania_frozen}`}>
    
                <p className={`${styles.copyright}`}>
                    © Your Website 2023. All Rights Reserved. Privacy · Terms · FAQ
                </p>
    
        </Row>
    
        </Row>
    
      </>
    )
};
