

/**
* Generated by ExoCoding 0.0.1
*/

import React from 'react';
import { useImmer } from 'use-immer';
import * as FontIcon from 'react-icons/fa';
import styles from './PasswordTemplate.module.css';
import useTitle from '@/hooks/useTitle';
import useBodystyle from '@/hooks/useBodystyle';
import { Container } from 'react-bootstrap';
import { Col } from 'react-bootstrap';
import { InputGroup } from 'react-bootstrap';
import { Form } from 'react-bootstrap';
import { Button } from 'react-bootstrap';
import { Row } from 'react-bootstrap';

type PasswordTemplateProps = {};

/**
* Forgot Your Password
*/
export const PasswordTemplate = (props: PasswordTemplateProps) => {

    useTitle('PasswordTemplate');

    return (
      <>
    
    <Container fluid="fluid" className={`d-flex ${styles.passwordtemplate} bg-primary`}>
    
    <Container fluid="md" className={`d-flex ${styles.from_soft} bg-`}>
    
    <Col  className={`d-flex ${styles.image}`}>
    </Col>
    
    
    <Col  className={`d-flex ${styles.content} bg-light`}>
    
                <p className={`${styles.forgotpasswordlabel}`}>
                    Forgot Your Password?
                </p>
    
    
                <p className={`${styles.passwordlabeltext}`}>
                    We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!
                </p>
    
    <Form.Group className={`${styles.inputemail}`}>
        <Form.Label>
            
        </Form.Label>
        <InputGroup>
            <InputGroup.Text><FontIcon.FaEnvelope/></InputGroup.Text>
            <Form.Control
                type="email"
placeholder="Enter Email Address..."
disabled={false}            />
        </InputGroup>
    </Form.Group>
    
        <Button
            variant="primary"
            className={`${styles.buttonresetpassword}`}
            
        >
                Reset Password

        </Button>
    
    
        <Row className={`${styles.accountrow}`}>
    
                <p className={`${styles.createanaccountlabel}`}>
                    Create an Account!
                </p>
    
    
                <p className={`${styles.haveanaccountlabel}`}>
                    Already have an account? Login!
                </p>
    
        </Row>
    
    </Col>
    
    </Container>
    
    </Container>
    
      </>
    )
};
