

/**
* Generated by ExoCoding 0.0.1
*/

import React from 'react';
import { useImmer } from 'use-immer';
import * as FontIcon from 'react-icons/fa';
import styles from './Resume_Template.module.css';
import useTitle from '@/hooks/useTitle';
import useBodystyle from '@/hooks/useBodystyle';
import { Container } from 'react-bootstrap';
import { Row } from 'react-bootstrap';
import { Nav } from 'react-bootstrap';
import { LinkContainer } from 'react-bootstrap';
import { Button } from 'react-bootstrap';
import { Col } from 'react-bootstrap';

type Resume_TemplateProps = {};

/**
* test
*/
export const Resume_Template = (props: Resume_TemplateProps) => {

    useTitle('Resume Template');

    return (
      <>
    
    <Container fluid="fluid" className={`d-flex ${styles.sidbar} bg-`}>
    
        <Row className={`${styles.navbar}`}>
    
        <img className={`figure-img ${styles.account_dynamic}`} src={`https://startbootstrap.github.io/startbootstrap-resume/assets/img/profile.jpg`} alt='' title=''/>
    
        </Row>
    
    
        <Row className={`${styles.syndicate_west}`}>
    
        <Row className={`${styles.clarencetaylor}`}>
    
        <Row className={`${styles.liberian_orange}`}>
    
                <p className={`${styles.clarence}`}>
                    CLARENCE 
                </p>
    
    
                <p className={`${styles.taylor}`}>
                    TAYLOR
                </p>
    
        </Row>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.state_orchid} bg-`}>
    
                <p className={`${styles.berkshire_north}`}>
                    3542 BERRY STREET · CHEYENNE WELLS, CO 80810 · (317) 585-8468
                </p>
    
    
                <p className={`${styles.labelemail}`}>
                     · NAME@EMAIL.COM
                </p>
    
    </Container>
    
    
                <p className={`${styles.gracefully_an}`}>
                    I am experienced in leveraging agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition.
                </p>
    
    
        <Row className={`${styles.blue_maroon}`}>
    
        <Button
            variant=""
            className={`${styles.canadian_auto}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaLinkedinIn />
    </div>
                null

        </Button>
    
    
        <Button
            variant=""
            className={`${styles.up_driver}`}
            
        >
    <div className='d-inline' style={{  marginRight: 'nullpx',  }}>
       <FontIcon.FaGithub size={null}/>
    </div>
                null

        </Button>
    
    
        <Button
            variant=""
            className={`${styles.run_array}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaTwitter />
    </div>
                null

        </Button>
    
    
        <Button
            variant=""
            className={`${styles.eaque_evidence}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaFacebookF />
    </div>
                null

        </Button>
    
        </Row>
    
        </Row>
    
    
        <Row className={`${styles.experience}`}>
    
                <p className={`${styles.experience}`}>
                    EXPERIENCE
                </p>
    
    
        <Row className={`${styles.seniorweb}`}>
    
        <Row className={`${styles.global_diesel}`}>
    
    <Col sm={5} className={`d-flex ${styles.youngstown_communicant}`}>
    
                <p className={`${styles.seniorwebdeveloper}`}>
                    SENIOR WEB DEVELOPER
                </p>
    
    
                <p className={`${styles.intelitecsolutions}`}>
                    INTELITEC SOLUTIONS
                </p>
    
    </Col>
    
    
    <Col sm={3} className={`d-flex ${styles.console_leone}`}>
    
                <p className={`${styles.march}`}>
                    March 2013 - Present
                </p>
    
    </Col>
    
        </Row>
    
    
                <p className={`${styles.sleek_northwest}`}>
                    Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.
                </p>
    
        </Row>
    
    
        <Row className={`${styles.webdeveloper}`}>
    
        <Row className={`${styles.steel_loan}`}>
    
    <Col sm={5} className={`d-flex ${styles.punt_below}`}>
    
                <p className={`${styles.webdeveloper}`}>
                    WEB DEVELOPER
                </p>
    
    
                <p className={`${styles.intelitecsolutions}`}>
                    INTELITEC SOLUTIONS
                </p>
    
    </Col>
    
    
    <Col sm={3} className={`d-flex ${styles.rock_smtp}`}>
    
                <p className={`${styles.december}`}>
                    December 2011 - March 2013
                </p>
    
    </Col>
    
        </Row>
    
    
                <p className={`${styles.below_bugatti}`}>
                    Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.
                </p>
    
        </Row>
    
    
        <Row className={`${styles.juniorwebdesigner}`}>
    
        <Row className={`${styles.optical_male}`}>
    
    <Col sm={6} className={`d-flex ${styles.farad_man}`}>
    
                <p className={`${styles.juniorweb}`}>
                    JUNIOR WEB DESIGNER
                </p>
    
    
                <p className={`${styles.shoutme}`}>
                    SHOUT! MEDIA PRODUCTIONS
                </p>
    
    </Col>
    
    
    <Col sm={3} className={`d-flex ${styles.haiti_platforms}`}>
    
                <p className={`${styles.health_randomisation}`}>
                    July 2010 - December 2011
                </p>
    
    </Col>
    
        </Row>
    
    
                <p className={`${styles.planner_east}`}>
                    Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration.
                </p>
    
        </Row>
    
    
        <Row className={`${styles.webdesignintern}`}>
    
        <Row className={`${styles.northeast_lime}`}>
    
    <Col sm={6} className={`d-flex ${styles.selenium_moratorium}`}>
    
                <p className={`${styles.webdesignintern}`}>
                    WEB DESIGN INTERN
                </p>
    
    
                <p className={`${styles.reboot_convertible}`}>
                    SHOUT! MEDIA PRODUCTIONS
                </p>
    
    </Col>
    
    
    <Col sm={3} className={`d-flex ${styles.iron_ah}`}>
    
                <p className={`${styles.septemberlabel}`}>
                    September 2008 - June 2010
                </p>
    
    </Col>
    
        </Row>
    
    
                <p className={`${styles.reboot_silver}`}>
                    Collaboratively administrate empowmarkets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.
                </p>
    
        </Row>
    
        </Row>
    
    
        <Row className={`${styles.education}`}>
    
                <p className={`${styles.wagon_bypass}`}>
                    EDUCATION
                </p>
    
    
        <Row className={`${styles.universityofcoloradoboulder}`}>
    
        <Row className={`${styles.florida_northwest}`}>
    
    <Col sm={7} className={`d-flex ${styles.wagon_recumbent}`}>
    
                <p className={`${styles.universityofcoloradoboulder}`}>
                    UNIVERSITY OF COLORADO BOULDER
                </p>
    
    
                <p className={`${styles.bachelorofscience}`}>
                    BACHELOR OF SCIENCE
                </p>
    
    </Col>
    
    
    <Col sm={3} className={`d-flex ${styles.silently_center}`}>
    
                <p className={`${styles.vain_consequuntur}`}>
                    August 2006 - May 2010
                </p>
    
    </Col>
    
        </Row>
    
    
                <p className={`${styles.unimportant_chrysler}`}>
                    Computer Science - Web Development Track GPA: 3.23
                </p>
    
        </Row>
    
    
        <Row className={`${styles.jamesbuchananhighschool}`}>
    
    <Col sm={6} className={`d-flex ${styles.leading_neon}`}>
    
                <p className={`${styles.enhance_utah}`}>
                    JAMES BUCHANAN HIGH SCHOOL
                </p>
    
    
                <p className={`${styles.technologymagnet}`}>
                    TECHNOLOGY MAGNET PROGRAM
                </p>
    
    </Col>
    
    
    <Col sm={3} className={`d-flex ${styles.beauty_primary}`}>
    
                <p className={`${styles.circuit_handmade}`}>
                    August 2002 - May 2006
                </p>
    
    </Col>
    
    
                <p className={`${styles.gpa356}`}>
                    GPA: 3.56
                </p>
    
        </Row>
    
        </Row>
    
    
        <Row className={`${styles.skill}`}>
    
                <p className={`${styles.bicycle_east}`}>
                    SKILLS
                </p>
    
    
                <p className={`${styles.loan_surinam}`}>
                    PROGRAMMING LANGUAGES & TOOLS
                </p>
    
    
        <Row className={`${styles.imagesskill}`}>
    
        <Button
            variant=""
            className={`${styles.buttonskill}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaHtml5 size={40}/>
    </div>
                null

        </Button>
    
    
        <Button
            variant=""
            className={`${styles.buttonskill}`}
            
        >
                null

        </Button>
    
    
        <Button
            variant=""
            className={`${styles.buttonskill}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaAngular size={40}/>
    </div>
                null

        </Button>
    
    
        <Button
            variant=""
            className={`${styles.buttonskill}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaReact size={40}/>
    </div>
                null

        </Button>
    
    
        <Button
            variant=""
            className={`${styles.buttonskill}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaSass size={40}/>
    </div>
                null

        </Button>
    
    
        <Button
            variant=""
            className={`${styles.buttonskill}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaNodeJs size={40}/>
    </div>
                null

        </Button>
    
    
        <Button
            variant=""
            className={`${styles.buttonskill}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaLess size={40}/>
    </div>
                null

        </Button>
    
    
        <Button
            variant=""
            className={`${styles.buttonskill}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaWordpress size={40}/>
    </div>
                null

        </Button>
    
    
        <Button
            variant=""
            className={`${styles.buttonskill}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaGulp size={40}/>
    </div>
                null

        </Button>
    
    
        <Button
            variant=""
            className={`${styles.buttonskill}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaGrunt size={40}/>
    </div>
                null

        </Button>
    
    
        <Button
            variant=""
            className={`${styles.buttonskill}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaNpm size={40}/>
    </div>
                null

        </Button>
    
        </Row>
    
    
                <p className={`${styles.workflow}`}>
                    WORKFLOW
                </p>
    
    
        <Row className={`${styles.kia_global}`}>
    
                <p className={`${styles.mobilefirst}`}>
                    ✓  Agile Development & Scrum
                </p>
    
    
                <p className={`${styles.lesotho_card}`}>
                    ✓  Cross Browser Testing & Debugging
                </p>
    
    
                <p className={`${styles.thallium_bedfordshire}`}>
                    ✓  Cross Functional Teams
                </p>
    
        </Row>
    
        </Row>
    
    
        <Row className={`${styles.interests}`}>
    
                <p className={`${styles.labelinterests}`}>
                    INTERESTS
                </p>
    
    
                <p className={`${styles.cofactor_dynamic}`}>
                    Apart from being a web developer, I enjoy most of my time being outdoors. In the winter, I am an avid skier and novice ice climber. During the warmer months here in Colorado, I enjoy mountain biking, free climbing, and kayaking.
                </p>
    
    
                <p className={`${styles.hybrid_withdrawal}`}>
                    When forced indoors, I follow a number of sci-fi and fantasy genre movies and television shows, I am an aspiring chef, and I spend a large amount of my free time exploring the latest technology advancements in the front-end web development world.
                </p>
    
        </Row>
    
    
        <Row className={`${styles.pataca_southeast}`}>
    
                <p className={`${styles.awardscertifications}`}>
                    AWARDS & CERTIFICATIONS
                </p>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.administrator_research}`}>
    
        <Button
            variant=""
            className={`${styles.run_array}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaTrophy />
    </div>
                null

        </Button>
    
    
                <p className={`${styles.png_south}`}>
                    Google Analytics Certified Developer
                </p>
    
    </Container>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.administrator}`}>
    
        <Button
            variant=""
            className={`${styles.run_array}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaTrophy />
    </div>
                null

        </Button>
    
    
                <p className={`${styles.png_south}`}>
                    Mobile Web Specialist - Google Certification
                </p>
    
    </Container>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.research}`}>
    
        <Button
            variant=""
            className={`${styles.run_array}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaTrophy />
    </div>
                null

        </Button>
    
    
                <p className={`${styles.png_south}`}>
                    1st Place - University of Colorado Boulder - Emerging Tech Competition 2009
                </p>
    
    </Container>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.administrator_research}`}>
    
        <Button
            variant=""
            className={`${styles.run_array}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaTrophy />
    </div>
                null

        </Button>
    
    
                <p className={`${styles.png_south}`}>
                    1 st Place - University of Colorado Boulder - Adobe Creative Jam 2008 (UI Design Category)
                </p>
    
    </Container>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.administrator_research}`}>
    
        <Button
            variant=""
            className={`${styles.run_array}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaTrophy />
    </div>
                null

        </Button>
    
    
                <p className={`${styles.png_south}`}>
                    2 nd Place - University of Colorado Boulder - Emerging Tech Competition 2008
                </p>
    
    </Container>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.administrator_research}`}>
    
        <Button
            variant=""
            className={`${styles.run_array}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaTrophy />
    </div>
                null

        </Button>
    
    
                <p className={`${styles.png_south}`}>
                    1 st Place - James Buchanan High School - Hackathon 2006
                </p>
    
    </Container>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.administrator_research}`}>
    
        <Button
            variant=""
            className={`${styles.run_array}`}
            
        >
    <div className='d-inline' style={{  }}>
       <FontIcon.FaTrophy />
    </div>
                null

        </Button>
    
    
                <p className={`${styles.png_south}`}>
                    3 rd Place - James Buchanan High School - Hackathon 2005
                </p>
    
    </Container>
    
        </Row>
    
        </Row>
    
    </Container>
    
      </>
    )
};
