

/**
* Generated by ExoCoding 0.0.1
*/

import React from 'react';
import { useImmer } from 'use-immer';
import * as FontIcon from 'react-icons/fa';
import styles from './SettingsTemplate.module.css';
import useTitle from '@/hooks/useTitle';
import useBodystyle from '@/hooks/useBodystyle';
import { Row } from 'react-bootstrap';
import { Col } from 'react-bootstrap';
import { Form } from 'react-bootstrap';
import { Container } from 'react-bootstrap';
import { InputGroup } from 'react-bootstrap';

type SettingsTemplateProps = {};

/**
* A simple settings page
*/
export const SettingsTemplate = (props: SettingsTemplateProps) => {

    useTitle('SettingsTemplate');

    return (
      <>
    
        <Row className={`${styles.componentxLZQSzrakH}`}>
    
    <Col sm={3} className={`d-flex ${styles.componenthtOUpbGzvO}`}>
    
                <h1 className={`${styles.componentFmmoedAqck}`}>
                    Settings
                </h1>
    
    
                <p className={`${styles.componentzomhJORXgo}`}>
                    Account
                </p>
    
    
                <p className={`${styles.componentufVJSgorpv}`}>
                    Organizations
                </p>
    
    </Col>
    
    
    <Col sm={9} className={`d-flex ${styles.componentzTpTeNdVoJ}`}>
    
                <h1 className={`${styles.componentFXVJrhNVSV}`}>
                    Settings
                </h1>
    
    
    <Form.Group className={`${styles.componentfvLalcxKXV}`}>
        <Form.Label>
            Name
        </Form.Label>
        <Form.Control
            type="text"
        />
    </Form.Group>
    
    
    <Form.Group className={`${styles.componentBlfEemkHsf}`}>
        <Form.Label>
            Email
        </Form.Label>
        <Form.Control
            type="text"
        />
    </Form.Group>
    
    
    <Form.Group className={`${styles.componentajvYyoSzqb}`}>
        <Form.Label>
            Phone number
        </Form.Label>
        <Form.Control
            type="text"
        />
    </Form.Group>
    
    
    <Container fluid="md" className={`d-flex ${styles.componentOENsEoETJZ}`}>
    
    <Form.Check
        className={`${styles.componentyohPVWwcYm}`}
        type="checkbox"
        
        
        
        label="Yes"
    />
    
    
    <Form.Check
        className={`${styles.componentHUTGsyWJfC}`}
        type="checkbox"
        
        
        
        label="No"
    />
    
    </Container>
    
    <Form.Group className={`${styles.componentuBTCdwcCAy}`}>
        <Form.Label>
            Socials
        </Form.Label>
        <InputGroup>
            <InputGroup.Text><FontIcon.FaLink /></InputGroup.Text>
            <Form.Control
                type="url"
            />
        </InputGroup>
    </Form.Group>
    </Col>
    
        </Row>
    
      </>
    )
};
