

/**
* Generated by ExoCoding 0.0.1
*/


/**
* 
*/
export type TABLE3Obj = {
    // 
    idTABLE3: number;
}

/**
* 
*/
export type TABLE2Obj = {
    // 
    idTABLE2: number;
}

/**
* 
*/
export type TABLE1Obj = {
    // 
    idTABLE1: number;
}
