

/**
* Generated by ExoCoding 0.0.1
*/

/**
* 
*/
export interface TABLE3ObjDTO {
}

/**
* 
*/
export interface TABLE2ObjDTO {
}

/**
* 
*/
export interface TABLE1ObjDTO {
}


export * from "./TABLE3Controller";
export * from "./TABLE3Controller";
export * from "./TABLE1Controller";
export * from "./TABLE2Controller";
