

/**
* Generated by ExoCoding 0.0.1
*/

import { AxiosRequestConfig } from 'axios';
import { axios } from '@/lib/axios';
import { Page } from '@/types';
import { TABLE2Obj } from '@/modules/main/types';
import { TABLE2ObjDTO } from '.';

/**
* Update one TABLE2Obj
*
* @param {idTABLE2} CRUD key input parameter
* @param {body} CRUD object input parameter
* @param {options} Override http request option.
* @returns TABLE2Obj */
export const putTABLE2Obj = (idTABLE2:  number, body: TABLE2ObjDTO, options: AxiosRequestConfig = {}): Promise<TABLE2Obj> => {
    return axios.put(`/table2obj/{idtable2}`, body, options);
};

/**
* Delete one TABLE2Obj
*
* @param {idTABLE2} CRUD key input parameter
* @param {options} Override http request option.
* @returns TABLE2Obj */
export const deleteTABLE2Obj = (idTABLE2:  number, options: AxiosRequestConfig = {}): Promise<any> => {
    return axios.delete(`/table2obj/{idtable2}`, options);
};

/**
* Create one TABLE2Obj
*
* @param {body} CRUD object input parameter
* @param {options} Override http request option.
* @returns TABLE2Obj */
export const postTABLE2Obj = (body: TABLE2ObjDTO, options: AxiosRequestConfig = {}): Promise<any> => {
    return axios.post(`/table2obj`, body, options);
};

/**
* Read one TABLE2Obj
*
* @param {idTABLE2} CRUD key input parameter
* @param {options} Override http request option.
* @returns TABLE2Obj */
export const getTABLE2Obj = (idTABLE2:  number, options: AxiosRequestConfig = {}): Promise<TABLE2Obj> => {
    return axios.get(`/table2obj/{idtable2}`, options);
};
