

/**
* Generated by ExoCoding 0.0.1
*/

import { AxiosRequestConfig } from 'axios';
import { axios } from '@/lib/axios';
import { Page } from '@/types';
import { TABLE1Obj } from '@/modules/main/types';
import { TABLE1ObjDTO } from '.';

/**
* Read one TABLE1Obj
*
* @param {idTABLE1} CRUD key input parameter
* @param {options} Override http request option.
* @returns TABLE1Obj */
export const getTABLE1Obj = (idTABLE1:  number, options: AxiosRequestConfig = {}): Promise<TABLE1Obj> => {
    return axios.get(`/table1obj/{idtable1}`, options);
};

/**
* Delete one TABLE1Obj
*
* @param {idTABLE1} CRUD key input parameter
* @param {options} Override http request option.
* @returns TABLE1Obj */
export const deleteTABLE1Obj = (idTABLE1:  number, options: AxiosRequestConfig = {}): Promise<any> => {
    return axios.delete(`/table1obj/{idtable1}`, options);
};

/**
* Read a list of TABLE1Obj
*
* @param {options} Override http request option.
* @returns TABLE1Obj */
export const getTABLE1ObjList = (options: AxiosRequestConfig = {}): Promise<TABLE1Obj[]> => {
    return axios.get(`/table1objlist`, options);
};

/**
* Update one TABLE1Obj
*
* @param {idTABLE1} CRUD key input parameter
* @param {body} CRUD object input parameter
* @param {options} Override http request option.
* @returns TABLE1Obj */
export const putTABLE1Obj = (idTABLE1:  number, body: TABLE1ObjDTO, options: AxiosRequestConfig = {}): Promise<TABLE1Obj> => {
    return axios.put(`/table1obj/{idtable1}`, body, options);
};

/**
* Create one TABLE1Obj
*
* @param {body} CRUD object input parameter
* @param {options} Override http request option.
* @returns TABLE1Obj */
export const postTABLE1Obj = (body: TABLE1ObjDTO, options: AxiosRequestConfig = {}): Promise<TABLE1Obj> => {
    return axios.post(`/table1obj`, body, options);
};
