package com.artsoft.testeexo.mapper;

import com.artsoft.testeexo.dto.TABLE3ObjDTO;
import com.artsoft.testeexo.model.TABLE3;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocode.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public abstract class TABLE3ObjWriteMapper extends EntityMapper {

  public abstract TABLE3ObjDTO entityToDto ( TABLE3 entity );

  public abstract List<TABLE3ObjDTO> entityToDto ( List<TABLE3> entityList );

  public abstract TABLE3 dtoToEntity ( TABLE3ObjDTO dto );

  public abstract List<TABLE3> dtoToEntity ( List<TABLE3ObjDTO> dtoList );

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  public abstract void updateFromDto ( @MappingTarget TABLE3 entity, TABLE3ObjDTO dto );
}