package com.artsoft.testeexo.mapper;

import com.artsoft.testeexo.dto.TABLE3ObjDTO;
import com.artsoft.testeexo.model.TABLE3;
import com.artsoft.testeexo.schema.TABLE3ObjSchema;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocode.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public interface TABLE3ObjMapper {

  TABLE3ObjDTO entityToDto ( TABLE3 entity );

  List<TABLE3ObjDTO> entityToDto ( List<TABLE3> entityList );

  TABLE3 dtoToEntity ( TABLE3ObjDTO dto );

  List<TABLE3> dtoToEntity ( List<TABLE3ObjDTO> dtoList );

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  void updateFromDto ( @MappingTarget TABLE3 entity, TABLE3ObjDTO dto );

  TABLE3ObjSchema dtoToSchema ( TABLE3ObjDTO dto );

  List<TABLE3ObjSchema> dtoToSchema ( List<TABLE3ObjDTO> dtoList );

  TABLE3ObjDTO schemaToDto ( TABLE3ObjSchema schema );

  List<TABLE3ObjDTO> schemaToDto ( List<TABLE3ObjSchema> schemaList );
}