package com.artsoft.testeexo.mapper;

import com.artsoft.testeexo.dto.TABLE1ObjDTO;
import com.artsoft.testeexo.model.TABLE1;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.Mapper;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocode.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public abstract class TABLE1ObjReadMapper extends EntityMapper {

  public abstract TABLE1ObjDTO entityToDto ( TABLE1 entity );

  public abstract List<TABLE1ObjDTO> entityToDto ( List<TABLE1> entityList );
}