package com.artsoft.testeexo.mapper;

import com.artsoft.testeexo.dto.TABLE2ObjDTO;
import com.artsoft.testeexo.model.TABLE2;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocode.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public abstract class TABLE2ObjWriteMapper extends EntityMapper {

  public abstract TABLE2ObjDTO entityToDto ( TABLE2 entity );

  public abstract List<TABLE2ObjDTO> entityToDto ( List<TABLE2> entityList );

  public abstract TABLE2 dtoToEntity ( TABLE2ObjDTO dto );

  public abstract List<TABLE2> dtoToEntity ( List<TABLE2ObjDTO> dtoList );

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  public abstract void updateFromDto ( @MappingTarget TABLE2 entity, TABLE2ObjDTO dto );
}