package com.artsoft.testeexo.mapper;

import com.artsoft.testeexo.dto.TABLE2ObjDTO;
import com.artsoft.testeexo.model.TABLE2;
import com.artsoft.testeexo.schema.TABLE2ObjSchema;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocode.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public interface TABLE2ObjMapper {

  TABLE2ObjDTO entityToDto ( TABLE2 entity );

  List<TABLE2ObjDTO> entityToDto ( List<TABLE2> entityList );

  TABLE2 dtoToEntity ( TABLE2ObjDTO dto );

  List<TABLE2> dtoToEntity ( List<TABLE2ObjDTO> dtoList );

  @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
  void updateFromDto ( @MappingTarget TABLE2 entity, TABLE2ObjDTO dto );

  TABLE2ObjSchema dtoToSchema ( TABLE2ObjDTO dto );

  List<TABLE2ObjSchema> dtoToSchema ( List<TABLE2ObjDTO> dtoList );

  TABLE2ObjDTO schemaToDto ( TABLE2ObjSchema schema );

  List<TABLE2ObjDTO> schemaToDto ( List<TABLE2ObjSchema> schemaList );
}