package com.artsoft.testeexo.mapper;

import com.artsoft.testeexo.dto.TABLE3ObjDTO;
import com.artsoft.testeexo.model.TABLE3;
import java.util.List;
import javax.annotation.processing.Generated;
import org.mapstruct.Mapper;
import org.springframework.stereotype.Component;

@Generated(value = "com.exocode.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Component
@Mapper
public abstract class TABLE3ObjReadMapper extends EntityMapper {

  public abstract TABLE3ObjDTO entityToDto ( TABLE3 entity );

  public abstract List<TABLE3ObjDTO> entityToDto ( List<TABLE3> entityList );
}