package com.artsoft.testeexo.model;

import javax.annotation.processing.Generated;

/**
 * Abstract class common to all entities.
 */
@Generated(value = "com.exocode.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
public abstract class AbstractEntity {
}