package com.artsoft.testeexo.repos;

import com.artsoft.testeexo.model.TABLE3;
import javax.annotation.processing.Generated;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

@Generated(value = "com.exocode.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@Repository
public interface TABLE3Repository extends JpaRepository<TABLE3, Long>,
    JpaSpecificationExecutor<TABLE3> {

}