

/**
* Generated by ExoCoding 0.0.1
*/

import React from 'react';
import Modal from 'react-bootstrap/Modal';
import { useImmer } from 'use-immer';
import * as FontIcon from 'react-icons/fa';
import styles from './ModalTeste.module.css';

type ModalTesteProps = {
  show: boolean;
  onHide: () => void;
};

/**
* 
*/
export const ModalTeste = (props: ModalTesteProps) => {

    return (
      <Modal show={props.show} onHide={props.onHide} >
        <Modal.Header closeButton>
          <Modal.Title>
            modalTeste
          </Modal.Title>
        </Modal.Header>
        <Modal.Body>
        </Modal.Body>
      </Modal>
    )
};
