

/**
* Generated by ExoCoding 0.0.1
*/

import React from 'react';
import { useImmer } from 'use-immer';
import * as FontIcon from 'react-icons/fa';
import styles from './Layouttesting.module.css';
import { Nav } from 'react-bootstrap';
import { Navbar } from 'react-bootstrap';
import { Container } from 'react-bootstrap';
import { LinkContainer } from 'react-router-bootstrap';
import { NavDropdown } from 'react-bootstrap/NavDropdown';
import { Outlet } from 'react-router-dom';

type LayouttestingProps = {};

/**
* Header navbar
*/
export const Layouttesting = (props: LayouttestingProps) => {


    return (
      <>
    

        <Navbar bg="primary" expand="lg" className={`${styles.bespoke_transmitter}`}>
            <Container>
                <Navbar.Brand >
                    
                    Home
                </Navbar.Brand>
                <Navbar.Toggle aria-controls="basic-navbar-nav" />
                <Navbar.Collapse id="basic-navbar-nav">
                    <Nav className="me-auto">
                    </Nav>
                </Navbar.Collapse>
            </Container>
        </Navbar>
    
    
    <Container fluid="fluid" className={`d-flex ${styles.woman_gorgeous} bg-`}>
    <Outlet />
    </Container>
    
      </>
    )
};
